### ISSUE TITLE
Unable to convert Job Title and Organization fields

### ISSUE THREAD

**Issue by Appy22** [thomascube/vcfconvert#10]
Hi,
My firm requires contact information from iCloud to be converted to CSV format but recently these two fields: Job Title and Organization are not getting converted at all. Any help would be appreciated.
Thanks,
Appy

**Comment by thomascube** [comment]
Both fields are actually mapped in the converter and work for my test cases. Would you mind uploading an example vcard file which doesn't work?

**Comment by thomascube** [comment]
No feedback. Closing.
