### ISSUE TITLE
Memory issue for 2600 contacts

### ISSUE THREAD

**Issue by temn** [thomascube/vcfconvert#12]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 286024 bytes) in Contact_Vcard_Parse.php on line 354

**Comment by thomascube** [comment]
You need to increase the memory limit of your PHP installation via php.ini
Like described here: https://stackoverflow.com/questions/4660517/where-to-edit-for-increase-in-memory-in-php-ini-file
