### ISSUE TITLE
csv file to *.mab

### ISSUE THREAD

**Issue by PbIC9TuHa** [thomascube/vcfconvert#15]
Hi there! ask for ideas ! I need the script to convert the csv file to *.mab the address for thunderbird can't find it no where or anything

**Comment by PbIC9TuHa** [comment]
maybe vcf  =>  *.mab ???

**Comment by thomascube** [comment]
I don't know the mab address format but for converting vcard to thunderbird use this converter with the LDIF format. Anyway, we cannot convert CSV to anything only VCF.
