### ISSUE TITLE
cli skript

### ISSUE THREAD

**Issue by peterkaem** [thomascube/vcfconvert#20]
Hi Thomas,
on my linux mint 20.1 cinnamon
./vcfconvert.sh
=> /usr/bin/env: »php -qC“: Datei oder Verzeichnis nicht gefunden

then in
vcfconvert.sh
I changed
#!/usr/bin/env php -qC 
to
#!/usr/bin/php7.4 -qC 
and it runs well.

Thank You for Your great skipt!
Peter

**Comment by thomascube** [comment]
the `/usr/bin/env` command uses $PATH resolution to execute the given command. Simply create a symlink from /usr/bin/php -> /usr/bin/php7.4 in order to let your system know the "php" command.

Using /usr/bin/env in the shebang line is a common pattern and I don't thinks we should change the script.
