### ISSUE TITLE
Change GitHub's website link to HTTPS

### ISSUE THREAD

**Issue by voidbert** [thomascube/vcfconvert#22]
# Issue
On the repository's about section, the link to the project's website is still using the HTTP protocol. I have tried to use HTTPS in the website and TLS seems to work.

# Request
I am kindly requesting the change of the project's website on the repository's settings to use HTTPS, in order to avoid traffic sniffing and other atacks. This simple change will drastically improve the security of users that get to your website through GitHub.

**Comment by thomascube** [comment]
Done. Thanks for the hint!
